eureka:
  client:
    fetch-service-url:
      defaultZone: http://localhost:8761/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    password: password
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
