server:
  port: 9091

eureka:
  client:
    fetch-service-url:
      defaultZone: http://localhost:8761/

spring:
  application:
    name: RESTAURANT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    password: password
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
